version: '3.4'
services:
  odoo:
    image: llacox/odoo:13.0
    volumes:
      - data:/var/lib/odoo
    command: --workers 3 --limit-time-cpu 1800 --limit-time-real 1800
    ports:
      - 47134:8069
      - 47135:8072
    restart: unless-stopped
    stdin_open: true
    tty: true
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: unless-stopped
volumes:
  data:
    name: infratel-dev_data
    external: true
  db-data:
    name: infratel-dev_db_data
    external: true
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.103.50.1/28
